Data Understanding

1.Load the dataset into pandas

In [3]:
import pandas as pd

In [5]:
df=pd.read_csv(r"C:\Users\IT\Desktop\Data Analysis\AnalystLab Africa Internship\OnlineRetail.csv\OnlineRetail_Original.csv",encoding='latin1')
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

2. Display the first few rows.

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

3. Identify:
- Number of rows and columns
- Data types of all columns
- Numerical features
- Categorical features
- Possible unique identifiers (primary keys)

In [9]:
#Number of rows and columns
df.shape

(541909, 8)

In [11]:
# Data types of all columns
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [14]:
# Numerical features
df.select_dtypes(include=['int64','float64']).columns

Index(['Quantity', 'UnitPrice', 'CustomerID'], dtype='str')

In [16]:
#Categorical features
df.select_dtypes(include=['object','string']).columns

Index(['InvoiceNo', 'StockCode', 'Description', 'InvoiceDate', 'Country'], dtype='str')

In [20]:
#Possible unique identifiers (primary keys)
df['StockCode'].nunique()

4372

In [21]:
df['InvoiceNo'].nunique()

25900

In [22]:
df['CustomerID'].nunique()

4372

In [16]:
#Check if any primary key is there in dataset
df['InvoiceNo'].is_unique
df['StockCode'].is_unique
df['CustomerID'].is_unique

False

In [9]:
len(df)

541909

4. Briefly describe what the dataset contains.

   This dataset contains online retail transaction records including invoice number,
   product code, product description, quantity purchased, invoice date,
   unit price, customer ID and country.